repos:
    - repo: 'https://github.com/pre-commit/pre-commit-hooks'
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: end-of-file-fixer
          - id: check-json
          - id: check-xml
          - id: check-yaml
          - id: trailing-whitespace
            exclude: \.gitignore$
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v3.1.0'
      hooks:
          - id: prettier
            {%- if cookiecutter.code_formatter_print_width != 0 %}
            args: ['--print-width', '{{ cookiecutter.code_formatter_print_width }}']
            {%- endif %}
            exclude: '\.(php)$'
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v8.56.0'
      hooks:
          - id: eslint
            args: [--fix]
    - repo: https://github.com/digitalpulp/pre-commit-php.git
      rev: 1.4.0
      hooks:
          - id: php-lint-all
    - repo: https://github.com/digitalpulp/pre-commit-php.git
      rev: 1.4.0
      hooks:
          - id: php-cbf
            files: \.(php)$
            args: [-p]
    - repo: https://github.com/digitalpulp/pre-commit-php.git
      rev: 1.4.0
      hooks:
          - id: php-cs
            files: \.(php)$
            args: [-p]

exclude: |
    (?x)^(
        .*\.min\.(js)$|
        composer\.json|
        composer\.lock|
        package\.json|
        package-lock\.json
    )$
