[tool.ruff]
# https://docs.astral.sh/ruff/
line-length = {{ cookiecutter.code_formatter_print_width }}


[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
extend-select = [
  "B",           # flake8-bugbear
  "I",           # isort
  # "ARG",         # flake8-unused-arguments
  # "C4",          # flake8-comprehensions
  # "EM",          # flake8-errmsg
  # "ICN",         # flake8-import-conventions
  # "G",           # flake8-logging-format
  # "PGH",         # pygrep-hooks
  "PIE",         # flake8-pie
  # "PL",          # pylint
  # "PT",          # flake8-pytest-style
  # "PTH",         # flake8-use-pathlib
  # "RET",         # flake8-return
  # "RUF",         # Ruff-specific
  # "SIM",         # flake8-simplify
  # "T20",         # flake8-print
  # "UP",          # pyupgrade
  # "YTT",         # flake8-2020
  # "EXE",         # flake8-executable
  # "NPY",         # NumPy specific rules
  # "PD",          # pandas-vet
  # "FURB",        # refurb
  # "PYI",         # flake8-pyi
]
