default_language_version:
  python: python3.10
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args:
          - '--maxkb=10000'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: end-of-file-fixer
        exclude: '\.ipynb$'
      - id: trailing-whitespace
      - id: pretty-format-json
      - id: check-symlinks
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
        args:
            - '--allow-missing-credentials'
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.1.2
    hooks:
      - id: ruff
      - id: ruff-format
