default_language_version:
  python: python3.11
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args:
          - '--maxkb=10000'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: end-of-file-fixer
        exclude: '\.ipynb$'
      - id: trailing-whitespace
      - id: check-symlinks
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
        args:
            - '--allow-missing-credentials'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        args: ["--print-width", "{{ cookiecutter.code_formatter_print_width }}"]
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: v0.1.2
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
