name: pre-commit

on:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.11'
            - name: Install PHP, composer and dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y php-cli php-xml php-curl composer
                  composer update
            - uses: actions/setup-node@v4
            - run: npm install @wordpress/prettier-config @wordpress/eslint-plugin --save-dev
            - uses: pre-commit/action@v3.0.0
