name: "Setup tests"
description: "Setup Python env for testing"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install Python dependencies
      shell: bash
      run: pip install cookiecutter pre-commit pytest pytest-order
