pipelines:
  default:
    - step:
        name: Lint
        image: python:3.11
        script:
          - pip install -q pre-commit
          - pre-commit run --show-diff-on-failure --color=always --all-files
