pipelines:
  default:
    - step:
        name: Lint
        image: python:3.11
        script:
          - apt-get update && apt-get install -y gnupg software-properties-common wget unzip
          - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee -a /etc/apt/sources.list.d/hashicorp.list
          - apt-get update && apt-get install terraform
          - pip install -q pre-commit
          - pre-commit run --show-diff-on-failure --color=always --all-files
