name: Generate and lint generated templates
on:
  workflow_dispatch: {}
  pull_request:
  push:
    branches: [main]

jobs:
  templating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
      - run: pip install cookiecutter pre-commit pytest pytest-order
      - run: pytest -m "not python_env"
